apiVersion: v1
kind: Service
metadata:
  labels:
    operated-thanos-ruler: "true"
  name: thanos-ruler-operated
  namespace: kubesphere-monitoring-system
 # ownerReferences:
 # - apiVersion: monitoring.coreos.com/v1
 #   kind: ThanosRuler
 #   name: kubesphere
 #   uid: 8db4bd8d-35b5-4704-af17-5f5d623e5c9e
 # resourceVersion: "378635"
 # uid: 281f58e6-2728-44bf-a6c4-51726126354d
spec:
  clusterIP: None
  ports:
  - name: web
    port: 10902
    protocol: TCP
    targetPort: web
  - name: grpc
    port: 10901
    protocol: TCP
    targetPort: grpc
  selector:
    app.kubernetes.io/name: thanos-ruler
  type: ClusterIP
status:
