apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-storage
  namespace: monitoring
spec:
  storageClassName: nfs-provisioner-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50G
