apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webkook-db-data
  namespace: monitoring
spec:
  storageClassName: "nas-nfs-provider"
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
