apiVersion: v1
kind: Service
metadata:
  name: webhook-service
  namespace: monitoring
spec:
  ports:
  - nodePort: 31330
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    k8s-app: webhook
  type: NodePort
