apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app.kubernetes.io/name: kube-prometheus
    app.kubernetes.io/part-of: kube-prometheus
    prometheus: k8s
    role: alert-rules
    release: kube-prometheus-stack
  name: kube-prometheus-stack-node-exporter
  namespace: monitoring
spec:
  groups:
  - name: node-exporter
    rules:
    - alert: 节点 CPU 使用率超过 50%
      annotations:
        description: 节点 {{$labels.instance}} 的 CPU 使用率已超过 50%，当前使用率为 {{ printf "%.2f" $value }}%。
        summary: 节点 CPU 使用率过高;
      expr: |-
        (sum(rate(node_cpu_seconds_total{mode!="idle"}[5m])) by (instance) /
         sum(rate(node_cpu_seconds_total[5m])) by (instance))
        * on(instance) group_left(nodename) node_uname_info * 100 > 50
      for: 5m
      labels:
        severity: warning

    - alert: 节点 CPU 使用率超过 80%
      annotations:
        description: 节点 {{$labels.instance}} 的 CPU 使用率已超过 80%，当前使用率为 {{ printf "%.2f" $value }}%节点即将面临POD驱逐风险
        summary: 节点 CPU 使用率过高;
      expr: |-
        (sum(rate(node_cpu_seconds_total{mode!="idle"}[5m])) by (instance) /
         sum(rate(node_cpu_seconds_total[5m])) by (instance))
        * on(instance) group_left(nodename) node_uname_info * 100 > 80
      for: 5m
      labels:
        severity: critical

    - alert: 节点内存使用率大于60%
      annotations:
        description: 在节点名 {{ $labels.nodename }} 节点IP ({{ $labels.instance }}) 上内存使用率为 {{ printf "%.2f" $value }}%
        summary: 节点内存即将耗尽
      expr: |-
        (1 - ((node_memory_MemFree_bytes{job="node-exporter"} + node_memory_Cached_bytes{job="node-exporter"} + node_memory_Buffers_bytes{job="node-exporter"}) 
              / node_memory_MemTotal_bytes{job="node-exporter"}))
        * on(instance) group_left(nodename) node_uname_info * 100 > 60
      for: 5m
      labels:
        severity: warning
    
    - alert: 节点内存使用率大于80%
      annotations:
        description: 在节点名 {{ $labels.nodename }} 节点IP ({{ $labels.instance }}) 上内存使用率为 {{ printf "%.2f" $value }}%. 节点即将面临POD驱逐风险
        summary: 节点内存即将耗尽
      expr: |-
        (1 - ((node_memory_MemFree_bytes{job="node-exporter"} + node_memory_Cached_bytes{job="node-exporter"} + node_memory_Buffers_bytes{job="node-exporter"}) 
              / node_memory_MemTotal_bytes{job="node-exporter"}))
        * on(instance) group_left(nodename) node_uname_info * 100 > 80
      for: 5m
      labels:
        severity: critical

    - alert: 节点文件系统即将耗尽空间
      expr: |-
        (node_filesystem_avail_bytes{fstype!="",job="node-exporter"} / node_filesystem_size_bytes{fstype!="",job="node-exporter"} * 100 < 40 
        and node_filesystem_readonly{fstype!="",job="node-exporter"} == 0) 
        * on(instance) group_left(nodename) node_uname_info
      for: 5m
      labels:
        cluster: critical
        type: node
      annotations:
        description: 节点 {{ $labels.nodename }} ({{ $labels.instance }}) 上的 {{ $labels.device }} 文件系统只剩下 {{ printf "%.2f" $value }}% 的可用空间。
        summary: 节点文件系统剩余空间不足 40%

    - alert: 节点文件系统空间
      annotations:
        description: 在 {{ $labels.instance }} 上的 {{ $labels.device }} 文件系统中只剩下 {{ printf "%.2f" $value }}% 的可用空间，并且正在迅速填满。
        runbook_url: https://runbooks.prometheus-operator.dev/runbooks/node/nodefilesystemspacefillingup 
        summary: 预测文件系统在未来24小时内将耗尽空间;
      expr: |-
        (
          node_filesystem_avail_bytes{job="node-exporter",fstype!=""} / node_filesystem_size_bytes{job="node-exporter",fstype!=""} * 100 < 15
        and
          predict_linear(node_filesystem_avail_bytes{job="node-exporter",fstype!=""}[6h], 24*60*60) < 0
        and
          node_filesystem_readonly{job="node-exporter",fstype!=""} == 0
        )
      for: 1h
      labels:
        severity: critical

    - alert: 节点文件系统几乎超出存储空间
      annotations:
        description: '节点 {{ $labels.nodename }} (实例: {{ $labels.instance }}, 设备: {{ $labels.device }}) 文件系统只剩下 {{ printf "%.2f" $value }}% 的可用空间。'
        runbook_url: https://runbooks.prometheus-operator.dev/runbooks/node/nodefilesystemalmostoutofspace
        summary: 文件系统只剩下不到40%的空间,
      expr: |-
        (
          node_filesystem_avail_bytes{job="node-exporter",fstype!=""} 
          / node_filesystem_size_bytes{job="node-exporter",fstype!=""} * 100 < 40
        and
          node_filesystem_readonly{job="node-exporter",fstype!=""} == 0
        )
        * on (instance) group_left(nodename) node_uname_info
      for: 30m
      labels:
        severity: warning

    - alert: 节点文件系统几乎超出存储空间
      annotations:
        description: '节点 {{ $labels.nodename }} (实例: {{ $labels.instance }}, 设备: {{ $labels.device }}) 文件系统只剩下 {{ printf "%.2f" $value }}% 的可用空间。'
        runbook_url: https://runbooks.prometheus-operator.dev/runbooks/node/nodefilesystemalmostoutofspace
        summary: 文件系统只剩下不到30%的空间,
      expr: |-
        (
          node_filesystem_avail_bytes{job="node-exporter",fstype!=""}
          / node_filesystem_size_bytes{job="node-exporter",fstype!=""} * 100 < 30
        and
          node_filesystem_readonly{job="node-exporter",fstype!=""} == 0
        )
        * on (instance) group_left(nodename) node_uname_info
      for: 30m
      labels:
        severity: warning

    - alert: 节点文件系统几乎超出存储空间
      annotations:
        description: '节点 {{ $labels.nodename }} (实例: {{ $labels.instance }}, 设备: {{ $labels.device }}) 文件系统只剩下 {{ printf "%.2f" $value }}% 的可用空间, POD即将面临被驱逐'
        runbook_url: https://runbooks.prometheus-operator.dev/runbooks/node/nodefilesystemalmostoutofspace
        summary: 文件系统只剩下不到20%的空间,
      expr: |-
        (
          node_filesystem_avail_bytes{job="node-exporter",fstype!=""}
          / node_filesystem_size_bytes{job="node-exporter",fstype!=""} * 100 < 20
        and
          node_filesystem_readonly{job="node-exporter",fstype!=""} == 0
        )
        * on (instance) group_left(nodename) node_uname_info
      for: 30m
      labels:
        severity: critical

    - alert: 节点文件系统几乎超出存储空间
      annotations:
        description: '节点 {{ $labels.nodename }} (实例: {{ $labels.instance }}, 设备: {{ $labels.device }}) 文件系统只剩下 {{ printf "%.2f" $value }}% 的可用空间, POD正在被驱逐'
        runbook_url: https://runbooks.prometheus-operator.dev/runbooks/node/nodefilesystemalmostoutofspace
        summary: 文件系统只剩下不到10%的空间,
      expr: |-
        (
          node_filesystem_avail_bytes{job="node-exporter",fstype!=""}
          / node_filesystem_size_bytes{job="node-exporter",fstype!=""} * 100 < 10
        and
          node_filesystem_readonly{job="node-exporter",fstype!=""} == 0
        )
        * on (instance) group_left(nodename) node_uname_info
      for: 30m
      labels:
        severity: critical

    - alert: 节点文件系统几乎超出存储空间
      annotations:
        description: '节点 {{ $labels.nodename }} (实例: {{ $labels.instance }}, 设备: {{ $labels.device }}) 文件系统只剩下 {{ printf "%.2f" $value }}% 的可用空间, POD正在被驱逐'
        runbook_url: https://runbooks.prometheus-operator.dev/runbooks/node/nodefilesystemalmostoutofspace
        summary: 文件系统只剩下不到5%的空间
      expr: |-
        (
          node_filesystem_avail_bytes{job="node-exporter",fstype!=""}
          / node_filesystem_size_bytes{job="node-exporter",fstype!=""} * 100 < 5
        and
          node_filesystem_readonly{job="node-exporter",fstype!=""} == 0
        )
        * on (instance) group_left(nodename) node_uname_info
      for: 30m
      labels:
        severity: critical

    - alert: 节点文件系统文件数填充过多
      annotations:
        description: 在 {{ $labels.instance }} 上的 {{ $labels.device }} 文件系统中只剩下 {{ printf "%.2f" $value }}% 的可用inode，并且正在迅速填满。
        runbook_url: https://runbooks.prometheus-operator.dev/runbooks/node/nodefilesystemfilesfillingup 
        summary: 预测文件系统在未来24小时内将耗尽inode;当inode数量不足时，即使磁盘空间还有剩余，也无法创建新的文件，这可能会影响系统和应用程序的正常运行。
      expr: |-
        (
          node_filesystem_files_free{job="node-exporter",fstype!=""} / node_filesystem_files{job="node-exporter",fstype!=""} * 100 < 40
        and
          predict_linear(node_filesystem_files_free{job="node-exporter",fstype!=""}[6h], 24*60*60) < 0
        and
          node_filesystem_readonly{job="node-exporter",fstype!=""} == 0
        )
      for: 1h
      labels:
        severity: critical
    - alert: 节点文件系统文件数填充过多
      annotations:
        description: 在 {{ $labels.instance }} 上的 {{ $labels.device }} 文件系统中只剩下 {{ printf "%.2f" $value }}% 的可用inode，并且正在迅速填满。
        runbook_url: https://runbooks.prometheus-operator.dev/runbooks/node/nodefilesystemfilesfillingup 
        summary: 预测文件系统在未来4小时内将耗尽inode;当inode数量不足时，即使磁盘空间还有剩余，也无法创建新的文件，这可能会影响系统和应用程序的正常运行。
      expr: |-
        (
          node_filesystem_files_free{job="node-exporter",fstype!=""} / node_filesystem_files{job="node-exporter",fstype!=""} * 100 < 20
        and
          predict_linear(node_filesystem_files_free{job="node-exporter",fstype!=""}[6h], 4*60*60) < 0
        and
          node_filesystem_readonly{job="node-exporter",fstype!=""} == 0
        )
      for: 1h
      labels:
        severity: critical
    - alert: 节点文件系统文件数填充过多
      annotations:
        description: 在 {{ $labels.instance }} 上的 {{ $labels.device }} 文件系统中只剩下 {{ printf "%.2f" $value }}% 的可用inode。
        runbook_url: https://runbooks.prometheus-operator.dev/runbooks/node/nodefilesystemalmostoutoffiles 
        summary: 文件系统只剩下不到5%的inode;当inode数量不足时，即使磁盘空间还有剩余，也无法创建新的文件，这可能会影响系统和应用程序的正常运行。
      expr: |-
        (
          node_filesystem_files_free{job="node-exporter",fstype!=""} / node_filesystem_files{job="node-exporter",fstype!=""} * 100 < 5
        and
          node_filesystem_readonly{job="node-exporter",fstype!=""} == 0
        )
      for: 1h
      labels:
        severity: critical
    - alert: 节点文件系统即将无可用文件数
      annotations:
        description: 在 {{ $labels.instance }} 上的 {{ $labels.device }} 文件系统中只剩下 {{ printf "%.2f" $value }}% 的可用inode。
        runbook_url: https://runbooks.prometheus-operator.dev/runbooks/node/nodefilesystemalmostoutoffiles 
        summary: 文件系统只剩下不到3%的inode;当inode数量不足时，即使磁盘空间还有剩余，也无法创建新的文件，这可能会影响系统和应用程序的正常运行。
      expr: |-
        (
          node_filesystem_files_free{job="node-exporter",fstype!=""} / node_filesystem_files{job="node-exporter",fstype!=""} * 100 < 3
        and
          node_filesystem_readonly{job="node-exporter",fstype!=""} == 0
        )
      for: 1h
      labels:
        severity: critical
    - alert: 节点网络接收错误
      annotations:
        description: '{{ $labels.instance }} 的 {{ $labels.device }} 接口在过去两分钟内遇到了 {{ printf "%.0f" $value }} 次接收错误。'
        runbook_url: https://runbooks.prometheus-operator.dev/runbooks/node/nodenetworkreceiveerrs 
        summary: 网络接口报告了许多接收错误;监控这些错误有助于及时发现网络问题，比如硬件故障、配置错误或者网络拥塞等问题，从而保证网络的稳定性和数据传输的可靠性。
      expr: rate(node_network_receive_errs_total[2m]) / rate(node_network_receive_packets_total[2m])
        > 0.01
      for: 1h
      labels:
        severity: critical
    - alert: 节点网络传输错误
      annotations:
        description: '{{ $labels.instance }} 的 {{ $labels.device }} 接口在过去两分钟内遇到了 {{ printf "%.0f" $value }} 次传输错误。'
        runbook_url: https://runbooks.prometheus-operator.dev/runbooks/node/nodenetworktransmiterrs 
        summary: 网络接口报告了许多传输错误;这些错误可能包括数据包发送失败、硬件故障、网络配置错误等。监控这些错误有助于及时发现并解决网络传输过程中的问题，确保数据能够正确、高效地发送到目标地址。
      expr: rate(node_network_transmit_errs_total[2m]) / rate(node_network_transmit_packets_total[2m])
        > 0.01
      for: 1h
      labels:
        severity: critical
    - alert: 节点连接跟踪条目使用率高
      annotations:
        description: '{{ $value | humanizePercentage }} 的conntrack条目已被使用。'
        runbook_url: https://runbooks.prometheus-operator.dev/runbooks/node/nodehighnumberconntrackentriesused 
        summary: conntrack的数量接近限制;当连接跟踪条目的使用率很高时，可能意味着网络流量很大，或者存在某些异常流量模式，这可能会导致连接跟踪表满，从而影响新的连接建立。
      expr: (node_nf_conntrack_entries / node_nf_conntrack_entries_limit) > 0.75
      labels:
        severity: critical
    - alert: 节点文本文件收集器抓取错误
      annotations:
        description: 'Node Exporter 文本文件收集器未能抓取数据'
        runbook_url: https://runbooks.prometheus-operator.dev/runbooks/node/nodetextfilecollectorscrapeerror 
        summary: Node Exporter 文本文件收集器抓取失败;如果TFC在抓取过程中遇到错误，比如文件不存在、权限问题或者文件格式错误等，这个规则就会触发警报。
      expr: node_textfile_scrape_error{job="node-exporter"} == 1
      labels:
        severity: critical
    - alert: 节点时钟偏差检测
      annotations:
        description: '{{ $labels.instance }} 的时钟与标准时间偏差超过300秒。确保此主机上正确配置了NTP。'
        runbook_url: https://runbooks.prometheus-operator.dev/runbooks/node/nodeclockskewdetected 
        summary: 检测到时钟偏差;在分布式系统中，时钟偏差可能会导致数据一致性问题、日志记录混乱、安全问题、性能问题。
      expr: |-
        (
          node_timex_offset_seconds > 0.05
        and
          deriv(node_timex_offset_seconds[5m]) >= 0
        )
        or
        (
          node_timex_offset_seconds < -0.05
          and
          deriv(node_timex_offset_seconds[5m]) <= 0
        )
      for: 10m
      labels:
        severity: critical
    - alert: 节点时钟未同步
      annotations:
        description: '{{ $labels.instance }} 的时钟未同步。确保此主机上配置了NTP。'
        runbook_url: https://runbooks.prometheus-operator.dev/runbooks/node/nodeclocknotsynchronising 
        summary: 时钟未同步;在分布式系统中，准确的时间同步是非常重要的，因为很多操作依赖于时间戳来确定事件的顺序或进行日志记录。
      expr: |-
        min_over_time(node_timex_sync_status[5m]) == 0
        and
        node_timex_maxerror_seconds >= 16
      for: 10m
      labels:
        severity: critical
    - alert: 节点RAID降级
      annotations:
        description: '{{ $labels.instance }} 上的 RAID 数组 {{ $labels.device }} 由于一个或多个磁盘故障处于降级状态。备用驱动器数量不足以自动修复问题。'
        runbook_url: https://runbooks.prometheus-operator.dev/runbooks/node/noderaiddegraded 
        summary: RAID 数组已降级;当RAID阵列降级时，虽然数据仍然可以访问，但失去了冗余保护，如果再有硬盘故障，数据可能会丢失。
      expr: node_md_disks_required - ignoring (state) (node_md_disks{state="active"})
        > 0
      for: 15m
      labels:
        severity: critical
    - alert: 节点RAID磁盘故障
      annotations:
        description: '{{ $labels.instance }} 上的 RAID 数组至少有一个设备发生故障。需要关注 {{ $labels.device }} 数组，可能需要更换磁盘。'
        runbook_url: https://runbooks.prometheus-operator.dev/runbooks/node/noderaiddiskfailure 
        summary: RAID 数组中的设备失败;RAID磁盘故障意味着至少有一块硬盘无法正常工作，这可能会导致数据丢失或RAID阵列降级。
      expr: node_md_disks{state="failed"} > 0
      labels:
        severity: warning
    - alert: 节点文件描述符限制
      annotations:
        description: '{{ $labels.instance }} 的文件描述符限制当前为 {{ printf "%.2f" $value }}%。'
        runbook_url: https://runbooks.prometheus-operator.dev/runbooks/node/nodefiledescriptorlimit 
        summary: 内核预计很快将耗尽文件描述符限制;如果文件描述符的使用量接近系统限制，可能会导致应用程序无法打开新的文件或网络连接，从而影响系统的正常运行。
      expr: |-
        (
          node_filefd_allocated{job="node-exporter"} * 100 / node_filefd_maximum{job="node-exporter"} > 70
        )
      for: 15m
      labels:
        severity: critical
    - alert: 节点文件描述符限制
      annotations:
        description: '{{ $labels.instance }} 的文件描述符限制当前为 {{ printf "%.2f" $value }}%。'
        runbook_url: https://runbooks.prometheus-operator.dev/runbooks/node/nodefiledescriptorlimit 
        summary: 内核预计很快将耗尽文件描述符限制;如果文件描述符的使用量接近系统限制，可能会导致应用程序无法打开新的文件或网络连接，从而影响系统的正常运行。
      expr: |-
        (
          node_filefd_allocated{job="node-exporter"} * 100 / node_filefd_maximum{job="node-exporter"} > 90
        )
      for: 15m
      labels:
        severity: critical
