apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app.kubernetes.io/name: kube-prometheus
    app.kubernetes.io/part-of: kube-prometheus
    prometheus: k8s
    role: alert-rules
    release: kube-prometheus-stack
  name: kube-prometheus-stack-etcd
  namespace: monitoring
spec:
  groups:
  - name: kube-etcd
    rules:
    - alert: "etcd 成员不足"
      annotations:
        message: 'etcd 集群 "": 成员数量不足（）。'
      expr: |
        sum(up{job=~".*etcd.*"} == bool 1) by (job) < ((count(up{job=~".*etcd.*"}) by (job) + 1) / 2)
      for: 3m
      labels:
        gseverity: critical
    
    - alert: "etcd 无领导者"
      annotations:
        message: 'etcd 集群 "{{ $labels.job }}": 成员 {{ $labels.instance }} 无领导者。'
      expr: |
        etcd_server_has_leader{job=~".*etcd.*"} == 0
      for: 1m
      labels:
        gseverity: critical
    
    - alert: "etcd 高 fsync 持续时间"
      annotations:
        message: 'etcd 集群 "{{ $labels.job }}": 99百分位的fsync持续时间为 {{ $value }}s（正常应小于10ms），etcd实例 {{ $labels.instance }}。'
      expr: |
        histogram_quantile(0.99, rate(etcd_disk_wal_fsync_duration_seconds_bucket{job=~".*etcd.*"}[5m])) > 0.5
      for: 3m
      labels:
        gseverity: warning
    
    - alert: "etcd 高提交持续时间"
      annotations:
        message: 'etcd 集群 "": 99百分位的提交持续时间为 s（正常应小于120ms），etcd实例 。'
      expr: |
        histogram_quantile(0.99, rate(etcd_disk_backend_commit_duration_seconds_bucket{job=~".*etcd.*"}[5m])) > 0.25
      for: 3m
      labels:
        gseverity: warning
    
    - alert: "etcd 节点 RTT 持续时间过高"
      annotations:
        message: 'etcd 集群 "": 节点RTT持续时间为 s，etcd实例 。'
      expr: |
        histogram_quantile(0.99, rate(etcd_network_peer_round_trip_time_seconds_bucket[5m])) > 0.5
      for: 3m
      labels:
        gseverity: warning
    
    - alert: "etcd 磁盘空间不足"
      annotations:
        message: 'etcd 集群 "": etcd 实例 的磁盘空间不足。'
      expr: |
        node_filesystem_avail_bytes{job=~".*etcd.*", mountpoint="/"} / node_filesystem_size_bytes{job=~".*etcd.*", mountpoint="/"} < 0.1
      for: 5m
      labels:
        gseverity: critical
    
    - alert: "etcd 数据目录使用率过高"
      annotations:
        message: 'etcd 集群 "": 数据目录使用率超过 90% 的实例 。'
      expr: |
        etcd_debugging_mvcc_db_total_size_in_bytes{job=~".*etcd.*"} > 0.9 * node_filesystem_size_bytes{job=~".*etcd.*", mountpoint="/var/lib/etcd"}
      for: 5m
      labels:
        gseverity: warning
    
    - alert: "etcd Leader 频繁更换"
      annotations:
        message: 'etcd 集群 "": 领导者频繁更换，当前领导者为 。'
      expr: |
        increase(etcd_server_leader_changes_seen_total{job=~".*etcd.*"}[10m]) > 3
      for: 10m
      labels:
        gseverity: warning
    
    - alert: "etcd 同步数据失败"
      annotations:
        message: 'etcd 集群 "": etcd 实例 无法同步数据到其他节点。'
      expr: |
        rate(etcd_server_proposals_failed_total{job=~".*etcd.*"}[5m]) > 0
      for: 5m
      labels:
        gseverity: critical
    
    - alert: "etcd 存储碎片化"
      annotations:
        message: 'etcd 集群 "": etcd 实例 的存储碎片化过高，建议优化存储或重新压缩。'
      expr: |
        etcd_debugging_store_compaction_keys_total{job=~".*etcd.*"} > 10000
      for: 10m
      labels:
        gseverity: warning
    
    - alert: "etcd 网络延迟过高"
      annotations:
        message: 'etcd 集群 "": 节点间网络延迟过高，可能导致同步数据变慢。'
      expr: |
        histogram_quantile(0.99, rate(etcd_network_peer_round_trip_time_seconds_bucket[5m])) > 1
      for: 5m
      labels:
        gseverity: critical
