apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app.kubernetes.io/name: kube-prometheus
    app.kubernetes.io/part-of: kube-prometheus
    prometheus: k8s
    role: alert-rules
    release: kube-prometheus-stack
  name: kube-prometheus-stack-kubernetes-system-apiserver
  namespace: monitoring
spec:
  groups:
  - name: kubernetes-system-apiserver
    rules:
    - alert: KubeClientCertificateExpiration
      annotations:
        description: 用于向 Kubernetes API 服务器进行身份验证的客户端证书将在不到 7.0 天后过期。
        runbook_url: https://runbooks.prometheus-operator.dev/runbooks/kubernetes/kubeclientcertificateexpiration 
        summary: 客户端证书即将过期。
      expr: apiserver_client_certificate_expiration_seconds_count{job="apiserver"}
        > 0 and on(job) histogram_quantile(0.01, sum by (job, le) (rate(apiserver_client_certificate_expiration_seconds_bucket{job="apiserver"}[5m])))
        < 604800
      labels:
        severity: warning
    - alert: KubeClientCertificateExpiration
      annotations:
        description: 用于向 Kubernetes API 服务器进行身份验证的客户端证书将在不到 24.0 小时后过期。
        runbook_url: https://runbooks.prometheus-operator.dev/runbooks/kubernetes/kubeclientcertificateexpiration 
        summary: 客户端证书即将过期。
      expr: apiserver_client_certificate_expiration_seconds_count{job="apiserver"}
        > 0 and on(job) histogram_quantile(0.01, sum by (job, le) (rate(apiserver_client_certificate_expiration_seconds_bucket{job="apiserver"}[5m])))
        < 86400
      labels:
        severity: critical
    - alert: KubeAggregatedAPIErrors
      annotations:
        description: Kubernetes 聚合 API {{ $labels.name }}/{{ $labels.namespace }} 报告了错误。在过去的 10 分钟内平均出现了 {{ $value | humanize }} 次不可用的情况。
        runbook_url: https://runbooks.prometheus-operator.dev/runbooks/kubernetes/kubeaggregatedapierrors 
        summary: Kubernetes 聚合 API 报告了错误。
      expr: sum by(name, namespace)(increase(aggregator_unavailable_apiservice_total[10m]))
        > 4
      labels:
        severity: warning
    - alert: KubeAggregatedAPIDown
      annotations:
        description: Kubernetes 聚合 API {{ $labels.name }}/{{ $labels.namespace }} 在过去 10 分钟内仅 {{ $value | humanize }}% 的时间可用。
        runbook_url: https://runbooks.prometheus-operator.dev/runbooks/kubernetes/kubeaggregatedapidown 
        summary: Kubernetes 聚合 API 宕机。
      expr: (1 - max by(name, namespace)(avg_over_time(aggregator_unavailable_apiservice[10m])))
        * 100 < 85
      for: 5m
      labels:
        severity: warning
    - alert: KubeAPIDown
      annotations:
        description: KubeAPI 已从 Prometheus 目标发现中消失。
        runbook_url: https://runbooks.prometheus-operator.dev/runbooks/kubernetes/kubeapidown 
        summary: 目标从 Prometheus 目标发现中消失。
      expr: absent(up{job="apiserver"} == 1)
      for: 15m
      labels:
        severity: critical
    - alert: KubeAPITerminatedRequests
      annotations:
        description: Kubernetes API 服务器终止了 {{ $value | humanizePercentage }} 的传入请求。
        runbook_url: https://runbooks.prometheus-operator.dev/runbooks/kubernetes/kubeapiterminatedrequests 
        summary: Kubernetes API 服务器终止了 {{ $value | humanizePercentage }} 的传入请求。
      expr: sum(rate(apiserver_request_terminations_total{job="apiserver"}[10m]))  /
        (  sum(rate(apiserver_request_total{job="apiserver"}[10m])) + sum(rate(apiserver_request_terminations_total{job="apiserver"}[10m]))
        ) > 0.20
      for: 5m
      labels:
        severity: warning
