apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app.kubernetes.io/name: kube-prometheus
    app.kubernetes.io/part-of: kube-prometheus
    prometheus: k8s
    role: alert-rules
    release: kube-prometheus-stack
  name: kube-prometheus-stack-config-reloaders
  namespace: monitoring
spec:
  groups:
  - name: config-reloaders
    rules:
    - alert: ConfigReloaderSidecarErrors
      annotations:
        description: |-
          {{$labels.namespace}} 命名空间中的 {{$labels.pod}} 配置重新加载器 sidecar 尝试同步配置时遇到错误，因此，运行在 {{$labels.pod}} 上的服务配置可能已经过时且无法再更新
        runbook_url: https://runbooks.prometheus-operator.dev/runbooks/prometheus-operator/configreloadersidecarerrors
        summary: 配置重新加载器 sidecar 在 10 分钟内未成功重新加载
      expr: max_over_time(reloader_last_reload_successful{namespace=~".+"}[5m]) ==
        0
      for: 10m
      labels:
        severity: warning
