apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-mgr-exporter
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-mgr-exporter
  template:
    metadata:
      labels:
        app: mysql-mgr-exporter
    spec:
      containers:
        - name: mysql-mgr-exporter
          image: registry.cn-hangzhou.aliyuncs.com/tianxiang_app/mysql-mgr-exporter-mysql-8.0.21:v2
          ports:
            - containerPort: 8000
          env:
            - name: TZ
              value: Asia/Shanghai
            - name: MYSQL_HOST
              value: "192.168.233.223"
            - name: MYSQL_USER
              value: "exporter"
            - name: MYSQL_PASSWORD
              value: "123456"
            - name: MYSQL_DATABASE
              value: "performance_schema"
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-mgr-exporter
  namespace: monitoring
  labels:
    app: mysql-mgr-exporter  # 被 prometheus 抓到唯一标识
spec:
  selector:
    app: mysql-mgr-exporter
  ports:
    - name: mysql-mgr-exporter
      protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
