apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app.kubernetes.io/name: kube-prometheus
    app.kubernetes.io/part-of: kube-prometheus
    prometheus: k8s
    role: alert-rules
    release: kube-prometheus-stack
  name: mysql-mgr-exporter
  namespace: monitoring
spec:
  groups:
  - name: mysql-mgr-exporter
    rules:
    - alert: MySQLMGR成员数量为零
      expr: mysql_mgr_member_count == 0
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: "MySQL MGR 集群成员数量为 0"
        description: "MySQL MGR 集群成员数量为 0，可能集群已经崩溃或不存在成员。"

    - alert: MySQLMGR节点状态为离线
      expr: mysql_mgr_member_status == 0
      for: 10m
      labels:
        severity: critical
      annotations:
        summary: "MySQL MGR 节点处于 OFFLINE 状态"
        description: "MySQL MGR 节点处于 OFFLINE 状态，可能无法进行复制。"

    - alert: MySQLMGR主节点变更
      expr: changes(mysql_mgr_primary_member[10m]) > 0
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "MySQL MGR 主节点发生变化"
        description: "MySQL MGR 主节点在过去 10 分钟内发生了变化，请确认是否符合预期。"

    - alert: GTID执行事务数量低
      expr: mysql_gtid_executed_count < 80914401 # 根据实际的值修改: mysql> SELECT @@global.gtid_executed;
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "GTID 执行的事务数量低"
        description: "GTID 执行的事务数量低当前正常值，可能影响集群的事务处理能力。"

    - alert: MySQLMGR节点复制落后
      expr: mysql_mgr_lagging_members > 1000
      for: 10m
      labels:
        severity: warning
      annotations:
        summary: "MySQL MGR 节点复制落后"
        description: "某些 MySQL MGR 节点的复制落后事务数超过了 1000，可能影响集群的性能。"

    - alert: MySQLMGR事务冲突
      expr: mysql_mgr_conflicts > 0
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: "MySQL MGR 事务冲突"
        description: "MySQL MGR 检测到事务冲突，冲突次数大于 0，可能影响复制和一致性。"

    - alert: MySQLMGR GTID错误
      expr: mysql_mgr_gtid_errors > 0
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: "MySQL MGR GTID 错误"
        description: "MySQL MGR 检测到 GTID 错误，错误次数大于 0，可能影响事务一致性。"

    - alert: MySQLMGR未在单主模式
      expr: mysql_mgr_single_primary_mode == 0
      for: 10m
      labels:
        severity: critical
      annotations:
        summary: "MySQL MGR 不在单主模式"
        description: "MySQL MGR 当前没有处于单主模式，可能存在多个主节点。"
