apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app.kubernetes.io/name: kube-prometheus
    app.kubernetes.io/part-of: kube-prometheus
    prometheus: k8s
    role: alert-rules
    release: kube-prometheus-stack
  name: mysql-status-alarm
  namespace: mysql-cluster
spec:
  groups:
  - name: MySQL状态告警
    rules:
    - alert: MySQL服务宕机
      expr: mysql_up == 0
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: "实例 {{ .instance }} MySQL服务已宕机"
        description: "命名空间: {{ .namespace }}，Pod: {{ .pod }}，IP: {{ .instance }}。MySQL数据库服务不可用，需要立即处理！"
  
    - alert: 打开文件数过高
      expr: mysql_global_status_innodb_num_open_files > (mysql_global_variables_open_files_limit) * 0.75
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: "实例 {{ .instance }} 打开文件数过高"
        description: "命名空间: {{ .namespace }}，Pod: {{ .pod }}，IP: {{ .instance }}。当前打开文件数 ({{  }}) 超过 open_files_limit 的75%，请考虑增加 open_files_limit。"
  
    - alert: 读取缓冲区大小超过最大允许包大小
      expr: mysql_global_variables_read_buffer_size > mysql_global_variables_slave_max_allowed_packet
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: "实例 {{ .instance }} 读取缓冲区配置异常"
        description: "命名空间: {{ .namespace }}，Pod: {{ .pod }}，IP: {{ .instance }}。read_buffer_size 超过 max_allowed_packet，可能导致复制中断。当前值: {{  }}"
  
    - alert: 排序缓冲区可能配置不当
      expr: mysql_global_variables_innodb_sort_buffer_size <256*1024 or mysql_global_variables_read_buffer_size > 4*1024*1024
      for: 1m
      labels:
        severity: warning
      annotations:
        summary: "实例 {{ .instance }} 排序缓冲区配置异常"
        description: "命名空间: {{ .namespace }}，Pod: {{ .pod }}，IP: {{ .instance }}。排序缓冲区大小设置不当，建议 sort_buffer_size 设为 256KB 到 4MB 之间。当前值: {{  }}"
  
    - alert: 线程栈大小过小
      expr: mysql_global_variables_thread_stack < 196608
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: "实例 {{ .instance }} 线程栈大小不足"
        description: "命名空间: {{ .namespace }}，Pod: {{ .pod }}，IP: {{ .instance }}。线程栈大小过小，可能导致存储过程执行失败。当前值: {{  }}"
  
    - alert: 连接数超过最大限制的80%
      expr: mysql_global_status_max_used_connections > mysql_global_variables_max_connections * 0.8
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: "实例 {{ .instance }} 连接数使用超过阈值"
        description: "命名空间: {{ .namespace }}，Pod: {{ .pod }}，IP: {{ .instance }}。连接数超过最大值的80%，当前值: {{  }}"
  
    - alert: InnoDB强制恢复模式已启用
      expr: mysql_global_variables_innodb_force_recovery != 0
      for: 1m
      labels:
        severity: warning
      annotations:
        summary: "实例 {{ .instance }} 处于InnoDB强制恢复模式"
        description: "命名空间: {{ .namespace }}，Pod: {{ .pod }}，IP: {{ .instance }}。InnoDB强制恢复模式已启用，当前值: {{  }}"
  
    - alert: InnoDB日志文件大小过小
      expr: mysql_global_variables_innodb_log_file_size < 16777216
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: "实例 {{ .instance }} InnoDB日志文件配置过小"
        description: "命名空间: {{ .namespace }}，Pod: {{ .pod }}，IP: {{ .instance }}。InnoDB日志文件太小，可能影响性能，当前值: {{  }}"
  
    - alert: InnoDB事务提交日志刷盘配置异常
      expr: mysql_global_variables_innodb_flush_log_at_trx_commit != 1
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: "实例 {{ .instance }} 事务日志刷盘配置异常"
        description: "命名空间: {{ .namespace }}，Pod: {{ .pod }}，IP: {{ .instance }}。该参数不为1，可能在断电时造成数据丢失，当前值: {{  }}"
  
    - alert: 表定义缓存过小
      expr: mysql_global_status_open_table_definitions > mysql_global_variables_table_definition_cache
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: "实例 {{ .instance }} 表定义缓存不足"
        description: "命名空间: {{ .namespace }}，Pod: {{ .pod }}，IP: {{ .instance }}。表定义缓存不足，当前值: {{  }}"
  
    - alert: 表打开缓存过小
      expr: mysql_global_status_open_tables > mysql_global_variables_table_open_cache * 99/100
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: "实例 {{ .instance }} 表打开缓存不足"
        description: "命名空间: {{ .namespace }}，Pod: {{ .pod }}，IP: {{ .instance }}。表缓存不足，当前值: {{  }}"
  
    - alert: 线程栈大小可能不足
      expr: mysql_global_variables_thread_stack < 262144
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: "实例 {{ .instance }} 线程栈配置预警"
        description: "命名空间: {{ .namespace }}，Pod: {{ .pod }}，IP: {{ .instance }}。线程栈大小可能不足，当前值: {{  }}"
  
    - alert: InnoDB缓冲池实例数过少
      expr: mysql_global_variables_innodb_buffer_pool_instances == 1
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: "实例 {{ .instance }} 缓冲池实例数不足"
        description: "命名空间: {{ .namespace }}，Pod: {{ .pod }}，IP: {{ .instance }}。建议根据内存及核心数配置多个缓冲池实例。当前值: {{  }}"
  
    - alert: 二进制日志未启用
      expr: mysql_global_variables_log_bin != 1
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: "实例 {{ .instance }} 未启用二进制日志"
        description: "命名空间: {{ .namespace }}，Pod: {{ .pod }}，IP: {{ .instance }}。未启用 binlog，会导致无法进行时间点恢复（PiTR）"
  
    - alert: 二进制日志缓存大小不足
      expr: mysql_global_variables_binlog_cache_size < 1048576
      for: 1m
      labels:
        severity: warning
      annotations:
        summary: "实例 {{ .instance }} 二进制日志缓存过小"
        description: "命名空间: {{ .namespace }}，Pod: {{ .pod }}，IP: {{ .instance }}。建议设置为不小于1MB，当前值: {{  }}"
  
    - alert: 二进制日志语句缓存大小不足
      expr: mysql_global_variables_binlog_stmt_cache_size <1048576 and mysql_global_variables_binlog_stmt_cache_size > 0
      for: 1m
      labels:
        severity: warning
      annotations:
        summary: "实例 {{ .instance }} 二进制日志语句缓存过小"
        description: "命名空间: {{ .namespace }}，Pod: {{ .pod }}，IP: {{ .instance }}。建议设置为不小于1MB，当前值: {{  }}"
  
    - alert: 二进制日志事务缓存大小不足
      expr: mysql_global_variables_binlog_cache_size  <1048576
      for: 1m
      labels:
        severity: warning
      annotations:
        summary: "实例 {{ .instance }} 二进制日志事务缓存过小"
        description: "命名空间: {{ .namespace }}，Pod: {{ .pod }}，IP: {{ .instance }}。建议设置为不小于1MB，当前值: {{  }}"
  
    - alert: 二进制日志同步已启用
      expr: mysql_global_variables_sync_binlog == 1
      for: 1m
      labels:
        severity: warning
      annotations:
        summary: "实例 {{ .instance }} 二进制日志同步已开启"
        description: "命名空间: {{ .namespace }}，Pod: {{ .pod }}，IP: {{ .instance }}。sync_binlog=1 增强数据安全性，但可能降低写入性能"
  
    - alert: 从库未设置为只读模式(请忽略此警告)
      expr: mysql_global_variables_read_only != 0
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: "实例 {{ .instance }} 从库未设只读"
        description: "命名空间: {{ .namespace }}，Pod: {{ .pod }}，IP: {{ .instance }}。从库未设为只读，可能导致主从数据不一致"
