apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app.kubernetes.io/name: kube-prometheus
    app.kubernetes.io/part-of: kube-prometheus
    prometheus: k8s
    role: alert-rules
    release: kube-prometheus-stack
  name: mysql-system-alarm
  namespace: mysql-cluster
spec:
  groups:
  - name: MySQL主机监控告警
    rules:
    # -------------------------------
    # CPU使用率过高告警（超过80%持续5分钟）
    # -------------------------------
    - alert: CPU使用率过高
      expr: |
        100 - (
          avg by(instance, nodename) (
            rate(node_cpu_seconds_total{mode="idle"}[1m])
            * on(instance) group_left(nodename)
            node_uname_info{nodename=~".*mysql.*"}
          ) * 100
        ) > 80
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: "{{.nodename}} CPU使用率过高 ({{.instance}})"
        description: 'CPU使用率已达 {{ | printf "%.1f" }}%'
    # -------------------------------
    # 内存使用率过高告警（超过90%持续5分钟）
    # -------------------------------
    - alert: 内存使用率过高
      expr: |
        (
          1 - (
            node_memory_MemAvailable_bytes
            /
            node_memory_MemTotal_bytes
            * on(instance) group_left(nodename)
            node_uname_info{nodename=~".*mysql.*"}
          )
        ) * 100 > 90
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: "{{.nodename}} 内存使用率过高"
        description: '内存使用率: {{ | printf "%.1f"}}%,目前已经大于90%'

    # -------------------------------
    # 根分区磁盘使用率过高告警（超过85%持续1小时）
    # -------------------------------
    - alert: 根分区磁盘空间不足
      expr: |
        100 - (
          node_filesystem_avail_bytes{mountpoint="/"}
          /
          node_filesystem_size_bytes{mountpoint="/"}
          * on(instance) group_left(nodename)
          node_uname_info{nodename=~".*mysql.*"}
          * 100
        ) > 85
      for: 1h
      labels:
        severity: critical
      annotations:
        summary: "{{.nodename}} 根分区空间不足"
        description: '磁盘使用率: {{ | printf "%.1f"}}%,目前已经大于85%'

    # -------------------------------
    # OpenEBS磁盘使用率过高告警（超过90%持续30分钟）
    # -------------------------------
    - alert: OpenEBS存储空间不足
      expr: |
        100 - (
          node_filesystem_avail_bytes{mountpoint="/var/openebs"}
          /
          node_filesystem_size_bytes{mountpoint="/var/openebs"}
          * on(instance) group_left(nodename)
          node_uname_info{nodename=~".*mysql.*"}
          * 100
        ) > 80
      for: 30m
      labels:
        severity: critical
      annotations:
        summary: "紧急: {{.nodename}} OpenEBS存储将满"
        description: ' 存储使用率: {{ | printf "%.1f"}}%,目前已经大于80%'

    # -------------------------------
    # 磁盘空间预测告警（4天内将写满）
    # -------------------------------
    - alert: 磁盘将在4天内写满
      expr: |
        predict_linear(node_filesystem_avail_bytes{mountpoint="/var/openebs"}[6h], 4 * 86400) < 0
      labels:
        severity: critical
      annotations:
        summary: "紧急: {{.nodename}} 磁盘将在4天内写满"
        description: '根据6小时增长趋势，/var/openebs即将写满'

    # -------------------------------
    # 网络丢包率告警（bond0网卡，丢包率>1%持续5分钟）
    # -------------------------------
    - alert: 网络丢包率过高
      expr: |
        # 计算bond0总丢包率（接收+发送）
        (
          (
            rate(node_network_receive_errs_total{device="bond0"}[5m])
            +
            rate(node_network_transmit_errs_total{device="bond0"}[5m])
          )
          /
          (
            rate(node_network_receive_packets_total{device="bond0"}[5m])
            +
            rate(node_network_transmit_packets_total{device="bond0"}[5m])
            > 0  # 避免除零错误
          )
          * 100
        )
        * on(instance) group_left(nodename)
        node_uname_info{nodename=~".*mysql.*"} > 1
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: "{{.nodename}} bond0丢包率过高"
        description: |
          bond0总丢包率: {{ | printf "%.2f"}}%
          最近5分钟错误包: {{ | printf "%.0f"}} 个

    # -------------------------------
    # 网络接收带宽告警（bond0网卡）
    # -------------------------------
    - alert: 网络接收带宽过高
      expr: |
        (
          # 计算bond0接收带宽（Mbps）
          rate(node_network_receive_bytes_total{device="bond0"}[5m]) * 8 / 1000000
          # 关联主机名
          * on(instance) group_left(nodename)
          node_uname_info{nodename=~".*mysql.*"}
        ) > 600  # 阈值设为600Mbps（根据实际带宽调整）
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: "{{.nodename}} 网络带宽使用过高"
        description: ' 网卡 bond0 接收带宽: {{  | printf "%.1f" }} Mbps'

    # -------------------------------
    # 网络发送带宽告警（bond0网卡）
    # -------------------------------
    - alert: 网络发送带宽过高
      expr: |
        (
          rate(node_network_transmit_bytes_total{device="bond0"}[5m]) * 8 / 1000000
          * on(instance) group_left(nodename)
          node_uname_info{nodename=~".*mysql.*"}
        ) > 600
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: "{{.nodename}} 网络发送带宽过高"
        description: '发送带宽: {{  | printf "%.1f" }} Mbps'
