apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app.kubernetes.io/name: kube-prometheus
    app.kubernetes.io/part-of: kube-prometheus
    prometheus: k8s
    role: alert-rules
    release: kube-prometheus-stack
  name: mysql-system-alarm
  namespace: mysql-cluster
spec:
  groups:
  - name: MySQL主机监控告警
    rules:
    # -------------------------------
    # CPU使用率过高告警（超过80%持续5分钟）
    # -------------------------------
    - alert: CPU使用率过高
      expr: |
        100 - (
          avg by(instance, nodename) (
            rate(node_cpu_seconds_total{mode="idle"}[1m])
            * on(instance) group_left(nodename)
            node_uname_info{nodename=~".*mysql.*"}
          ) * 100
        ) > 80
      for: 5m
      labels:
        severity: mysql-critical
      annotations:
        summary: "{{.nodename}} CPU使用率过高 ({{.instance}})"
        description: |
          CPU使用率已达 {{ | printf "%.1f"}}%
          请检查: top - 19:55:51 up 330 days,  8:39,  2 users,  load average: 0.00, 0.03, 0.03
Tasks: 109 total,   1 running, 108 sleeping,   0 stopped,   0 zombie
%Cpu(s):  3.2 us,  0.0 sy,  0.0 ni, 96.8 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
MiB Mem :   1890.1 total,     84.2 free,    283.9 used,   1521.9 buff/cache
MiB Swap:      0.0 total,      0.0 free,      0.0 used.   1420.8 avail Mem 

    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
2405656 root      20   0  686260  17476  13660 S   6.7   0.9   1:22.49 aliyun-service
2446446 root      20   0   11716   3700   3244 R   6.7   0.2   0:00.01 top
      1 root      20   0  169364   9564   5340 S   0.0   0.5  82:06.09 systemd
      2 root      20   0       0      0      0 S   0.0   0.0   0:05.56 kthreadd
      3 root       0 -20       0      0      0 I   0.0   0.0   0:00.00 rcu_gp
      4 root       0 -20       0      0      0 I   0.0   0.0   0:00.00 rcu_par_gp
      6 root       0 -20       0      0      0 I   0.0   0.0   0:00.00 kworker/0:0H-kblockd
      8 root       0 -20       0      0      0 I   0.0   0.0   0:00.00 mm_percpu_wq
      9 root      20   0       0      0      0 S   0.0   0.0   6:38.57 ksoftirqd/0
     10 root      20   0       0      0      0 I   0.0   0.0 248:13.20 rcu_sched
     11 root      rt   0       0      0      0 S   0.0   0.0   1:19.34 migration/0
     12 root     -51   0       0      0      0 S   0.0   0.0   0:00.00 idle_inject/0
     14 root      20   0       0      0      0 S   0.0   0.0   0:00.00 cpuhp/0

    # -------------------------------
    # 内存使用率过高告警（超过90%持续5分钟）
    # -------------------------------
    - alert: 内存使用率过高
      expr: |
        (
          1 - (
            node_memory_MemAvailable_bytes
            /
            node_memory_MemTotal_bytes
            * on(instance) group_left(nodename)
            node_uname_info{nodename=~".*mysql.*"}
          )
        ) * 100 > 90
      for: 5m
      labels:
        severity: mysql-critical
      annotations:
        summary: "{{.nodename}} 内存使用率过高"
        description: '内存使用率: {{ | printf "%.1f"}}%,目前已经大于90%'

    # -------------------------------
    # 根分区磁盘使用率过高告警（超过85%持续1小时）
    # -------------------------------
    - alert: 根分区磁盘空间不足
      expr: |
        100 - (
          node_filesystem_avail_bytes{mountpoint="/"}
          /
          node_filesystem_size_bytes{mountpoint="/"}
          * on(instance) group_left(nodename)
          node_uname_info{nodename=~".*mysql.*"}
          * 100
        ) > 85
      for: 1h
      labels:
        severity: mysql-critical
      annotations:
        summary: "{{.nodename}} 根分区空间不足"
        description: '磁盘使用率: {{ | printf "%.1f"}}%,目前已经大于85%'

    # -------------------------------
    # OpenEBS磁盘使用率过高告警（超过90%持续30分钟）
    # -------------------------------
    - alert: OpenEBS存储空间不足
      expr: |
        100 - (
          node_filesystem_avail_bytes{mountpoint="/var/openebs"}
          /
          node_filesystem_size_bytes{mountpoint="/var/openebs"}
          * on(instance) group_left(nodename)
          node_uname_info{nodename=~".*mysql.*"}
          * 100
        ) > 80
      for: 30m
      labels:
        severity: critical
      annotations:
        summary: "紧急: {{.nodename}} OpenEBS存储将满"
        description: ' 存储使用率: {{ | printf "%.1f"}}%,目前已经大于80%'

    # -------------------------------
    # 磁盘空间预测告警（4天内将写满）
    # -------------------------------
    - alert: 磁盘将在4天内写满
      expr: |
        predict_linear(node_filesystem_avail_bytes{mountpoint="/var/openebs"}[6h], 4 * 86400) < 0
      labels:
        severity: critical
      annotations:
        summary: "紧急: {{.nodename}} 磁盘将在4天内写满"
        description: '根据6小时增长趋势，/var/openebs即将写满'

    # -------------------------------
    # 网络丢包率告警（bond0网卡，丢包率>1%持续5分钟）
    # -------------------------------
    - alert: 网络丢包率过高
      expr: |
        # 计算bond0总丢包率（接收+发送）
        (
          (
            rate(node_network_receive_errs_total{device="bond0"}[5m])
            +
            rate(node_network_transmit_errs_total{device="bond0"}[5m])
          )
          /
          (
            rate(node_network_receive_packets_total{device="bond0"}[5m])
            +
            rate(node_network_transmit_packets_total{device="bond0"}[5m])
            > 0  # 避免除零错误
          )
          * 100
        )
        * on(instance) group_left(nodename)
        node_uname_info{nodename=~".*mysql.*"} > 1
      for: 5m
      labels:
        severity: mysql-critical
      annotations:
        summary: "{{.nodename}} bond0丢包率过高"
        description: |
          bond0总丢包率: {{ | printf "%.2f"}}%
          最近5分钟错误包: {{ | printf "%.0f"}} 个

    # -------------------------------
    # 网络接收带宽告警（bond0网卡）
    # -------------------------------
    - alert: 网络接收带宽过高
      expr: |
        (
          # 计算bond0接收带宽（Mbps）
          rate(node_network_receive_bytes_total{device="bond0"}[5m]) * 8 / 1000000
          # 关联主机名
          * on(instance) group_left(nodename)
          node_uname_info{nodename=~".*mysql.*"}
        ) > 600  # 阈值设为600Mbps（根据实际带宽调整）
      for: 5m
      labels:
        severity: mysql-critical
      annotations:
        summary: "{{.nodename}} 网络带宽使用过高"
        description: ' 网卡 bond0 接收带宽: {{  | printf "%.1f" }} Mbps'

    # -------------------------------
    # 网络发送带宽告警（bond0网卡）
    # -------------------------------
    - alert: 网络发送带宽过高
      expr: |
        (
          rate(node_network_transmit_bytes_total{device="bond0"}[5m]) * 8 / 1000000
          * on(instance) group_left(nodename)
          node_uname_info{nodename=~".*mysql.*"}
        ) > 600
      for: 5m
      labels:
        severity: mysql-critical
      annotations:
        summary: "{{.nodename}} 网络发送带宽过高"
        description: '发送带宽: {{  | printf "%.1f" }} Mbps'
