apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app.kubernetes.io/name: kube-prometheus
    app.kubernetes.io/part-of: kube-prometheus
    prometheus: k8s
    role: alert-rules
    release: kube-prometheus-stack
  name: mysql-exporter
  namespace: monitoring
spec:
  groups:
  - name: mysql-exporter
    rules:
    - alert: MysqlDown
      expr: mysql_up == 0
      for: 0m
      labels:
        severity: critical
      annotations:
        summary: MySQL 实例不可用 (实例 {{ $labels.instance }})
        description: "MySQL 实例在 {{ $labels.instance }} 不可用。\n  当前值 = {{ $value }}\n  标签 = {{ $labels }}"

    - alert: MysqlTooManyConnections(>80%)
      expr: max_over_time(mysql_global_status_threads_connected[1m]) / mysql_global_variables_max_connections * 100 > 80
      for: 2m
      labels:
        severity: warning
      annotations:
        summary: MySQL 连接数过多 (> 80%) (实例 {{ $labels.instance }})
        description: "MySQL 实例 {{ $labels.instance }} 的连接数超过 80%。\n  当前值 = {{ $value }}\n  标签 = {{ $labels }}"

    - alert: MysqlHighPreparedStatementsUtilization(>80%)
      expr: max_over_time(mysql_global_status_prepared_stmt_count[1m]) / mysql_global_variables_max_prepared_stmt_count * 100 > 80
      for: 2m
      labels:
        severity: warning
      annotations:
        summary: MySQL 预处理语句使用率过高 (> 80%) (实例 {{ $labels.instance }})
        description: "MySQL 实例 {{ $labels.instance }} 的预处理语句使用率超过 80%。\n  当前值 = {{ $value }}\n  标签 = {{ $labels }}"

    - alert: MysqlHighThreadsRunning
      expr: max_over_time(mysql_global_status_threads_running[1m]) / mysql_global_variables_max_connections * 100 > 60
      for: 2m
      labels:
        severity: warning
      annotations:
        summary: MySQL 活跃线程过多 (实例 {{ $labels.instance }})
        description: "MySQL 实例 {{ $labels.instance }} 的活跃线程超过 60%。\n  当前值 = {{ $value }}\n  标签 = {{ $labels }}"

    - alert: MysqlSlaveIoThreadNotRunning
      expr: ( mysql_slave_status_slave_io_running and ON (instance) mysql_slave_status_master_server_id > 0 ) == 0
      for: 0m
      labels:
        severity: critical
      annotations:
        summary: MySQL 从库 IO 线程未运行 (实例 {{ $labels.instance }})
        description: "MySQL 从库的 IO 线程在 {{ $labels.instance }} 未运行。\n  当前值 = {{ $value }}\n  标签 = {{ $labels }}"

    - alert: MysqlSlaveSqlThreadNotRunning
      expr: ( mysql_slave_status_slave_sql_running and ON (instance) mysql_slave_status_master_server_id > 0) == 0
      for: 0m
      labels:
        severity: critical
      annotations:
        summary: MySQL 从库 SQL 线程未运行 (实例 {{ $labels.instance }})
        description: "MySQL 从库的 SQL 线程在 {{ $labels.instance }} 未运行。\n  当前值 = {{ $value }}\n  标签 = {{ $labels }}"

    - alert: MysqlSlaveReplicationLag
      expr: ( (mysql_slave_status_seconds_behind_master - mysql_slave_status_sql_delay) and ON (instance) mysql_slave_status_master_server_id > 0 ) > 30
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: MySQL 从库复制延迟过大 (实例 {{ $labels.instance }})
        description: "MySQL 实例 {{ $labels.instance }} 的复制延迟超过 30 秒。\n  当前值 = {{ $value }}\n  标签 = {{ $labels }}"

    - alert: MysqlSlowQueries
      expr: increase(mysql_global_status_slow_queries[1m]) > 0
      for: 2m
      labels:
        severity: warning
      annotations:
        summary: MySQL 慢查询 (实例 {{ $labels.instance }})
        description: "MySQL 实例 {{ $labels.instance }} 发生新的慢查询。\n  当前值 = {{ $value }}\n  标签 = {{ $labels }}"

    - alert: MysqlInnodbLogWaits
      expr: rate(mysql_global_status_innodb_log_waits[15m]) > 10
      for: 0m
      labels:
        severity: warning
      annotations:
        summary: MySQL InnoDB 日志等待过多 (实例 {{ $labels.instance }})
        description: "MySQL 实例 {{ $labels.instance }} 的 InnoDB 日志写入出现卡顿。\n  当前值 = {{ $value }}\n  标签 = {{ $labels }}"

    - alert: MysqlRestarted
      expr: mysql_global_status_uptime < 60
      for: 0m
      labels:
        severity: info
      annotations:
        summary: MySQL 刚刚重启 (实例 {{ $labels.instance }})
        description: "MySQL 实例 {{ $labels.instance }} 在一分钟内刚刚重启。\n  当前值 = {{ $value }}\n  标签 = {{ $labels }}"
